language: node_js
node_js:
  - "8.11"
services:
  - mongodb
cache:
  yarn: true
  directories: node_modules
git:
  depth: 3
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
